7.19. Оптимизация графики
htmlacademy-adaptive/2158229-cat-energy-27 pull request #8
Opened 2023-01-20 20:07 UTC by NADVooDoo

д/з 7.19. Оптимизация графики

2023-01-22 16:28 UTC, pavel-nyukalo requested changes
На 1440px вот такая ситуация возникает

![image](https://user-images.githubusercontent.com/52506235/213926983-dddc5607-a439-4b3b-afa2-c0e591d115c4.png)

Так же по макету на десктопе этих полосок нет

![image](https://user-images.githubusercontent.com/52506235/213926997-0be85bd1-e758-4cc4-9a05-769c2d81dd9e.png)

И на 768px тоже так же. В каталоге и форме все хорошо с этим

![image](https://user-images.githubusercontent.com/52506235/213927037-29fd05b5-38ba-4bdd-a502-dce52a0d3965.png)

2023-01-22 16:28 UTC, pavel-nyukalo commented on source/index.html
> +              <span class="slider__hidden">Ползунок слайдера</span>
`visually-hidden`?

2023-01-22 16:40 UTC, NADVooDoo commented on source/index.html
> +              <span class="slider__hidden">Ползунок слайдера</span>
Не подходит.
`.slider__hidden {
  position: fixed;
  transform: scale(0);
}`

2023-01-22 18:34 UTC, pavel-nyukalo requested changes
Оригиналы? Русских букв не должно быть

![image](https://user-images.githubusercontent.com/52506235/213933441-999bb306-9202-4a08-baf7-9687644f2a06.png)

2023-01-23 06:35 UTC, pavel-nyukalo approved these changes

2023-01-23 06:35 UTC, merged